Fix/staging.yml
s21platform/avatar-service pull request #8
Opened 2024-09-15 22:01 UTC by Snegov1k

Fix/staging.yml

2024-09-17 12:10 UTC, njohanne requested changes

2024-09-17 12:10 UTC, njohanne commented on internal/repository/s3storage/s3.go
> +type S3Storage interface {
вынести в отдельный файл contract.go

2024-09-17 12:10 UTC, njohanne commented on internal/repository/db/repository.go
> +func (r *Repository) GetAllAvatars(userUUID string) ([]string, error) {
Мы переходим на библиотеку sqlx. Посмотри в моем сервисе, у тебя гетер уменьшится в 5 раз. Советую сделать это сейчас пока не так много надо менять

2024-09-18 18:48 UTC, alexseipopov requested changes

2024-09-18 18:48 UTC, alexseipopov commented on internal/repository/db/repository.go
> +	S3Client   s3storage.S3Storage
Слой репозитория не должен делать ничего, кроме своей целевой задачи - работа с БД. Работа с S3 не должна происходить в этом слое.

работа с s3 происходит в отдельном слое, там соответственно одна цель - работа с s3 и все

По хорошему каскад вызовов s3 и БД в слое сервиса должны быть

2024-09-18 18:48 UTC, alexseipopov commented on internal/repository/db/repository.go
> +func (r *Repository) GetAllAvatars(userUUID string) ([]string, error) {
@Snegov1k тут согласен. Давайте сразу переедем на  sqlx

2024-09-18 18:48 UTC, alexseipopov commented on internal/repository/s3storage/s3.go
> +type S3Storage interface {
Это как раз контракт для service.go

2024-09-18 18:48 UTC, alexseipopov commented on internal/service/contract.go
> +}
Вот тут нужен s3 интерфейс тот что выше

2024-09-18 18:48 UTC, alexseipopov commented on internal/service/service.go
> +func New(repo DBRepo) *Service {
вот суюда надо s3 передавать как службу и тут сначала сохранять в s3 а потом в БД

2024-09-23 04:33 UTC, alexseipopov requested changes

2024-09-23 04:33 UTC, alexseipopov commented on cmd/service/main.go
> +	s3Client, err := s3storage.New(
Тут лучше передать cfg целиком, а данные из него извлекать уже там, в функции

2024-09-23 04:33 UTC, alexseipopov commented on cmd/service/main.go
> +		true,
и true лучше захардкодить уже там, в вызове функции и не передавать

2024-09-23 04:33 UTC, alexseipopov commented on internal/repository/s3storage/s3.go
> +		Secure: useSSL,
Вот тут true прям вписать. Наврятли мы будем как то иначе с этим работать

2024-09-23 04:33 UTC, alexseipopov commented on internal/repository/s3storage/s3.go
> +	_ "image/jpeg" // register the JPEG format for image decoding
Тут скорее просто вопрос. это осталось от рвнних попыток, или это типо возможный входящий формат?

2024-09-23 05:11 UTC, Snegov1k commented on internal/repository/s3storage/s3.go
> +	_ "image/jpeg" // register the JPEG format for image decoding
Это возможный входящий формат. Без него и image/png insomnia пишет, что не удалось декодировать изображение, тк неизвестный формат. 
Эти два импорта нужны для конвертации изображения в webp

2024-09-24 14:11 UTC, alexseipopov approved these changes

2024-09-27 11:38 UTC, njohanne approved these changes

2024-09-28 11:11 UTC, merged